version: "3.1"

volumes: # persistance when running 
    prometheus_data: {}
    grafana_data: {}

networks: # docker bridge labels
  front-tier:
  back-tier:

services: # define services containers
  prometheus:
    image: prom/prometheus:v2.53.0
    volumes: # map container folders for volumes
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks: # backend
      - back-tier

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes: # map container folders for volumes
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - .env
    networks: # front end
      - back-tier
      - front-tier

  metrics: # this gets github stats for monitor data 
    tty: true
    stdin_open: true
    expose:
      - 9504
    ports:
      - 9504:9504
    image: promhippie/github-exporter:latest
    restart: always
    environment: # REPOS mapped below 
      - GITHUB_EXPORTER_TOKEN=${GITHUB_EXPORTER_TOKEN}
      - GITHUB_EXPORTER_LOG_PRETTY=true
      - GITHUB_EXPORTER_REPO=obsidionz/build-test-contain,obsidionz/L00196753_IaC
    networks: # backend
      - back-tier
